<?php

use Illuminate\Database\Seeder;

class SubCelebritiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sub_celebrities')->delete();
        
        \DB::table('sub_celebrities')->insert(array (
            0 => 
            array (
                'id' => 2,
                'username' => '123',
                'password' => NULL,
                'email' => NULL,
                'user_first_name' => NULL,
                'user_last_name' => NULL,
                'name' => 'Muzafar Ali',
                'nicknames' => NULL,
                'birth_name' => NULL,
                'relation' => NULL,
                'industry' => NULL,
                'birth_place' => NULL,
                'bio' => 'bess bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio',
                'trade_mark' => NULL,
                'details_trivia' => NULL,
                'personal_quotes' => NULL,
                'profile_pic' => 'uploads/user/profile/profile_picture/06-2016/1466272865.png',
                'dob' => '1986-02-02',
                'gender' => '',
                'occupation' => '<p>OccupationOccupation bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio </p>',
                'rss' => '  <p><br></p><p>afdasdfasdfasdfbio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio 
bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio bio 
bio bio bio </p><p> </p>',
                'height' => '5.9',
                'salary' => '1000000',
                'popular_searches' => '  DXXdc, seDXXdc',
                'website' => '',
                'featured_video' => ' <iframe width="560" height="315" src="https://www.youtube.com/embed/Y4XoVnyiL8Q" frameborder="0" allowfullscreen></iframe>',
                'is_feature' => 0,
                'feature_subtitle' => NULL,
                'user_phone_number' => NULL,
                'user_home_number' => NULL,
                'user_address1' => NULL,
                'user_url_id' => NULL,
                'user_status' => 1,
                'created_on' => '2016-04-24 00:04:48',
            ),
            1 => 
            array (
                'id' => 3,
                'username' => '124',
                'password' => NULL,
                'email' => NULL,
                'user_first_name' => NULL,
                'user_last_name' => NULL,
                'name' => 'Muzafar Ali',
                'nicknames' => NULL,
                'birth_name' => NULL,
                'relation' => NULL,
                'industry' => NULL,
                'birth_place' => NULL,
                'bio' => 'BIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IO',
                'trade_mark' => NULL,
                'details_trivia' => NULL,
                'personal_quotes' => NULL,
                'profile_pic' => 'uploads/user/profile/profile_picture/06-2016/1466273094.JPG',
                'dob' => '1986-02-02',
                'gender' => '',
                'occupation' => 'BIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO',
                'rss' => '    BIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IOBIO BIOBI OBIOB IOBIOBI OBIOBI OBIOBIO IO',
                'height' => '5.6',
                'salary' => '100000',
                'popular_searches' => '   DXXdcDXXdc',
                'website' => '',
                'featured_video' => '   <iframe width="560" height="315" src="https://www.youtube.com/embed/Y4XoVnyiL8Q" frameborder="0" allowfullscreen></iframe>',
                'is_feature' => 1,
                'feature_subtitle' => 'News',
                'user_phone_number' => NULL,
                'user_home_number' => NULL,
                'user_address1' => NULL,
                'user_url_id' => NULL,
                'user_status' => 1,
                'created_on' => '2016-04-24 00:11:09',
            ),
            2 => 
            array (
                'id' => 4,
                'username' => '125',
                'password' => NULL,
                'email' => NULL,
                'user_first_name' => NULL,
                'user_last_name' => NULL,
                'name' => 'JENNIFER LOPEZ',
                'nicknames' => NULL,
                'birth_name' => NULL,
                'relation' => NULL,
                'industry' => NULL,
                'birth_place' => NULL,
                'bio' => 'userfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfile',
                'trade_mark' => NULL,
                'details_trivia' => NULL,
                'personal_quotes' => NULL,
                'profile_pic' => '1461438892.jpg',
                'dob' => '1986-02-02',
                'gender' => '',
                'occupation' => 'userfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfile',
                'rss' => '     userfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfileuserfile',
                'height' => '5.6',
                'salary' => '100000',
                'popular_searches' => '    ',
                'website' => '',
                'featured_video' => '    ',
                'is_feature' => 0,
                'feature_subtitle' => NULL,
                'user_phone_number' => NULL,
                'user_home_number' => NULL,
                'user_address1' => NULL,
                'user_url_id' => NULL,
                'user_status' => 1,
                'created_on' => '2016-04-24 00:14:52',
            ),
            3 => 
            array (
                'id' => 5,
                'username' => '126',
                'password' => NULL,
                'email' => NULL,
                'user_first_name' => NULL,
                'user_last_name' => NULL,
                'name' => 'Muzafar Ali',
                'nicknames' => 'Zafari',
                'birth_name' => NULL,
                'relation' => NULL,
                'industry' => NULL,
                'birth_place' => NULL,
                'bio' => 'testing',
                'trade_mark' => NULL,
                'details_trivia' => NULL,
                'personal_quotes' => NULL,
                'profile_pic' => '',
                'dob' => '1935-02-14',
                'gender' => 'Female',
                'occupation' => '',
                'rss' => '',
                'height' => NULL,
                'salary' => NULL,
                'popular_searches' => NULL,
                'website' => '',
                'featured_video' => NULL,
                'is_feature' => 0,
                'feature_subtitle' => NULL,
                'user_phone_number' => NULL,
                'user_home_number' => NULL,
                'user_address1' => NULL,
                'user_url_id' => NULL,
                'user_status' => 1,
                'created_on' => '2016-11-26 01:31:16',
            ),
            4 => 
            array (
                'id' => 6,
                'username' => '127',
                'password' => NULL,
                'email' => NULL,
                'user_first_name' => NULL,
                'user_last_name' => NULL,
                'name' => 'Muzafar Ali',
                'nicknames' => 'Zafari',
                'birth_name' => NULL,
                'relation' => NULL,
                'industry' => NULL,
                'birth_place' => NULL,
                'bio' => 'here is settins',
                'trade_mark' => NULL,
                'details_trivia' => NULL,
                'personal_quotes' => NULL,
                'profile_pic' => '',
                'dob' => '1929-02-03',
                'gender' => 'Female',
                'occupation' => '',
                'rss' => '',
                'height' => NULL,
                'salary' => NULL,
                'popular_searches' => NULL,
                'website' => '',
                'featured_video' => NULL,
                'is_feature' => 0,
                'feature_subtitle' => NULL,
                'user_phone_number' => NULL,
                'user_home_number' => NULL,
                'user_address1' => NULL,
                'user_url_id' => NULL,
                'user_status' => 1,
                'created_on' => '2016-12-05 16:53:47',
            ),
            5 => 
            array (
                'id' => 7,
                'username' => '128',
                'password' => NULL,
                'email' => NULL,
                'user_first_name' => NULL,
                'user_last_name' => NULL,
                'name' => 'Muzafar Ali',
                'nicknames' => 'Zafari',
                'birth_name' => NULL,
                'relation' => NULL,
                'industry' => NULL,
                'birth_place' => NULL,
                'bio' => 'testings',
                'trade_mark' => NULL,
                'details_trivia' => NULL,
                'personal_quotes' => NULL,
                'profile_pic' => '',
                'dob' => '0000-00-00',
                'gender' => 'Female',
                'occupation' => '',
                'rss' => '',
                'height' => NULL,
                'salary' => NULL,
                'popular_searches' => NULL,
                'website' => '',
                'featured_video' => NULL,
                'is_feature' => 0,
                'feature_subtitle' => NULL,
                'user_phone_number' => NULL,
                'user_home_number' => NULL,
                'user_address1' => NULL,
                'user_url_id' => NULL,
                'user_status' => 1,
                'created_on' => '2016-12-12 17:30:20',
            ),
            6 => 
            array (
                'id' => 8,
                'username' => '129',
                'password' => NULL,
                'email' => NULL,
                'user_first_name' => NULL,
                'user_last_name' => NULL,
                'name' => 'Muzafar Ali',
                'nicknames' => 'Zafari',
                'birth_name' => NULL,
                'relation' => NULL,
                'industry' => NULL,
                'birth_place' => NULL,
                'bio' => 'testings',
                'trade_mark' => NULL,
                'details_trivia' => NULL,
                'personal_quotes' => NULL,
                'profile_pic' => '',
                'dob' => '0000-00-00',
                'gender' => 'Female',
                'occupation' => '',
                'rss' => '',
                'height' => NULL,
                'salary' => NULL,
                'popular_searches' => NULL,
                'website' => '',
                'featured_video' => NULL,
                'is_feature' => 0,
                'feature_subtitle' => NULL,
                'user_phone_number' => NULL,
                'user_home_number' => NULL,
                'user_address1' => NULL,
                'user_url_id' => NULL,
                'user_status' => 1,
                'created_on' => '2016-12-12 17:34:56',
            ),
            7 => 
            array (
                'id' => 9,
                'username' => 'Sternhagen',
                'password' => 'e10adc3949ba59abbe56e057f20f883e',
                'email' => 'admins@demo.com',
                'user_first_name' => 'Ezaan',
                'user_last_name' => 'Ahmad',
                'name' => 'Ezaan Ahmad',
                'nicknames' => 'Ezaan',
                'birth_name' => NULL,
                'relation' => 'Manager',
                'industry' => 'sports',
                'birth_place' => 'Okara',
                'bio' => 'here is description update',
                'trade_mark' => NULL,
                'details_trivia' => NULL,
                'personal_quotes' => NULL,
                'profile_pic' => '',
                'dob' => '1927-02-02',
                'gender' => 'Female',
                'occupation' => '',
                'rss' => '',
                'height' => NULL,
                'salary' => NULL,
                'popular_searches' => NULL,
                'website' => 'http://www.hakomat.com',
                'featured_video' => NULL,
                'is_feature' => 0,
                'feature_subtitle' => NULL,
                'user_phone_number' => '03224187786',
                'user_home_number' => '03224187786',
                'user_address1' => 'Lahore, Punjab Pakistan',
                'user_url_id' => '..0',
                'user_status' => 1,
                'created_on' => '2016-12-29 17:01:18',
            ),
        ));
        
        
    }
}